import Foundation

public enum FunPasteLanguage: String, Sendable {
    case english
    case simplifiedChinese

    public static var current: FunPasteLanguage {
        preferred(from: Locale.preferredLanguages)
    }

    public static func preferred(from languageIdentifiers: [String]) -> FunPasteLanguage {
        guard let identifier = languageIdentifiers.first?.lowercased() else { return .english }
        return identifier.hasPrefix("zh") ? .simplifiedChinese : .english
    }
}

public enum FunPasteLocalization {
    public static func string(
        _ key: String,
        language: FunPasteLanguage = .current
    ) -> String {
        let translations = language == .simplifiedChinese ? simplifiedChinese : english
        return translations[key] ?? english[key] ?? key
    }

    public static func format(
        _ key: String,
        language: FunPasteLanguage = .current,
        _ arguments: CVarArg...
    ) -> String {
        String(
            format: string(key, language: language),
            locale: language == .simplifiedChinese ? Locale(identifier: "zh-Hans") : Locale(identifier: "en"),
            arguments: arguments
        )
    }

    public static var hasCompleteTranslations: Bool {
        Set(english.keys) == Set(simplifiedChinese.keys)
    }

    private static let english: [String: String] = [
        "menu.show": "Show funPaste",
        "menu.resume": "Resume Clipboard Recording",
        "menu.pause": "Pause Clipboard Recording",
        "menu.clear": "Clear Clipboard History",
        "menu.quit": "Quit funPaste",
        "common.cancel": "Cancel",
        "common.copy": "Copy",
        "common.delete": "Delete",
        "common.edit": "Edit",
        "common.restore": "Restore",
        "common.archive": "Archive",
        "common.save": "Save",
        "common.create": "Create",
        "common.favorites": "Favorites",
        "common.category": "Category",
        "common.items.count": "%d items",
        "settings.title": "funPaste Settings",
        "settings.launchAtLogin": "Launch at Login",
        "settings.launchAtLogin.requiresApproval": "Allow funPaste in System Settings to finish enabling this option.",
        "settings.launchAtLogin.unavailable": "Launch at login is unavailable for this copy of funPaste.",
        "settings.launchAtLogin.openSystemSettings": "Open Login Item Settings",
        "settings.historyLimit": "Clipboard History Limit",
        "settings.historyLimit.count": "%d items",
        "close.funPaste": "Close funPaste",
        "category.switch": "Switch to %@",
        "category.recent": "Recent",
        "category.prompt": "Prompt",
        "category.pinned": "Favorites",
        "category.image": "Images",
        "category.file": "Files",
        "category.recent.headline": "What you just copied, right where you need it",
        "category.prompt.headline": "Keep your best prompts within reach",
        "category.pinned.headline": "Content worth using again and again",
        "category.image.headline": "Your latest copied images, all in one place",
        "category.file.headline": "Keep file references close at hand",
        "empty.title": "No matching content",
        "empty.description": "Try another keyword or browse a different category.",
        "prompt.new": "New Prompt",
        "favorite.new": "New Favorite",
        "editor.close": "Close Content Editor",
        "editor.prompt.new": "New Prompt",
        "editor.favorite.new": "New Favorite",
        "editor.prompt.edit": "Edit Prompt",
        "editor.favorite.edit": "Edit Favorite",
        "editor.variablesHint": "Use {{feature description}} and {{technical constraints}} as variables",
        "editor.prompt.titlePlaceholder": "Title, e.g. Implement a new feature",
        "editor.favorite.titlePlaceholder": "Title, e.g. Shipping address",
        "editor.prompt.contentPlaceholder": "Example: Help me implement...",
        "editor.favorite.contentPlaceholder": "Enter content you want to keep",
        "editor.primaryCollection": "Primary Category",
        "editor.tagsPlaceholder": "Tags, separated by commas",
        "editor.sourceURLPlaceholder": "Source URL (optional)",
        "search.prompt": "Search prompts, tags, or sources",
        "search.category": "Search %@",
        "delete.warning": "This action cannot be undone",
        "delete.confirmation": "Delete \u{201c}%@\u{201d}?",
        "delete.permanently": "Delete Permanently",
        "prompt.sort": "Prompt Sorting",
        "prompt.filter.all": "All",
        "prompt.filter.favorites": "Favorites",
        "prompt.filter.archived": "Archived",
        "prompt.favorite": "Favorite Prompt",
        "prompt.unfavorite": "Remove Prompt from Favorites",
        "favorite.add": "Add to Favorites",
        "favorite.added": "Favorited",
        "content.manage.prompt": "Manage Prompt",
        "content.manage.favorite": "Manage Favorite",
        "feedback.unpinned": "Removed \u{201c}%@\u{201d} from favorites",
        "feedback.pinned": "Favorited \u{201c}%@\u{201d}",
        "feedback.promptFavorited": "Favorited prompt \u{201c}%@\u{201d}",
        "feedback.promptUnfavorited": "Removed prompt \u{201c}%@\u{201d} from favorites",
        "feedback.archived": "Archived \u{201c}%@\u{201d}",
        "feedback.restored": "Restored \u{201c}%@\u{201d}",
        "feedback.emptyFields": "Title and content are required",
        "feedback.duplicate": "Duplicate content already exists: \u{201c}%@\u{201d}",
        "feedback.saved": "Saved \u{201c}%@\u{201d}",
        "feedback.deleted": "Deleted \u{201c}%@\u{201d}",
        "feedback.paused": "Clipboard recording paused",
        "feedback.resumed": "Clipboard recording resumed",
        "feedback.historyCleared": "Clipboard history cleared",
        "feedback.historyLimit": "Clipboard history limit set to %d items",
        "feedback.fileMissing": "The file was moved or deleted and has been removed from history",
        "feedback.someFilesMissing": "Some files are unavailable; only existing files were copied",
        "feedback.copiedManualPaste": "Copied. Paste it manually.",
        "feedback.pasted": "Pasted \u{201c}%@\u{201d}",
        "promptComposer.title": "Use Prompt",
        "promptComposer.templateContext": "Template Context",
        "promptComposer.templateDescription": "The template is read-only. Your input creates a one-time prompt.",
        "promptComposer.featureDescription": "Feature Description",
        "promptComposer.featureVariable": "Replaces {{feature description}} in the template",
        "promptComposer.featureGuidance": "Describe the goal, user scenario, and expected result",
        "promptComposer.technicalConstraints": "Technical Constraints",
        "promptComposer.technicalVariable": "Replaces {{technical constraints}} in the template",
        "promptComposer.technicalGuidance": "Enter the stack, compatibility, scope, or behavior that must not change",
        "promptComposer.additionalContext": "Additional Context",
        "promptComposer.additionalDescription": "Optional. Paste logs, code, references, or other long-form context.",
        "promptComposer.additionalGuidance": "Enter or paste additional information",
        "promptComposer.preview": "Generated Prompt Preview",
        "promptComposer.previewReady": "The complete content below will be copied or pasted.",
        "promptComposer.previewIncomplete": "Complete the required template variables first.",
        "promptComposer.guidance": "Tip: %@",
        "promptComposer.generateAndPaste": "Generate and Paste",
        "promptComposer.additionalSection": "Additional context:",
        "collection.inbox": "Inbox",
        "collection.development": "Development",
        "collection.research": "Research",
        "collection.writing": "Writing",
        "collection.productDesign": "Product Design",
        "collection.personal": "Personal",
        "sort.smart": "Smart Sort",
        "sort.recentlyUsed": "Recently Used",
        "sort.recentlyAdded": "Recently Added",
        "sort.name": "Name",
        "history.source.clipboard": "Clipboard",
        "history.image.title": "Clipboard Image",
        "history.image.description": "Image \u{00b7} %@",
        "history.files.count": "%d files",
        "library.source.customPrompt": "Custom Prompt",
        "library.source.favorite": "Favorite",
        "demo.productPrinciple.title": "Product experience comes first",
        "demo.productPrinciple.content": "I define the requirements; you choose the technical approach, architecture, and implementation. The top priority is the user experience.",
        "demo.productPrinciple.source": "Note",
        "demo.swiftUIFocus.title": "SwiftUI card focus state",
        "demo.appleHIG.content": "Design should be clear, predictable, and respectful of the system conventions people already know.",
        "demo.address.title": "Shipping address",
        "demo.address.content": "Personal studio \u{00b7} Please confirm the delivery time in advance",
        "demo.palette.title": "Soft sunset palette",
        "demo.palette.content": "Warm citrus, misty lilac, and deep ink blue",
        "demo.palette.source": "Screenshot",
        "demo.file.title": "funPaste product ideas.md",
        "demo.file.content": "A unified way to organize clipboard history, reusable content, and prompt templates.",
        "prompt.source.builtIn": "Built-in Prompt",
        "prompt.source.claude": "Claude Code Best Practices",
        "prompt.source.github": "GitHub Engineering Practices",
        "prompt.source.openAI": "OpenAI GPT-5.6 Guide",
        "prompt.development.title": "Help me implement this feature",
        "prompt.development.content": "Help me implement {{feature description}}.\n\nTechnical constraints: {{technical constraints}}.\n\nFirst inspect the project structure, explain the proposed changes, implement them, and run the relevant checks.",
        "prompt.plainLanguage.title": "Explain something complex clearly",
        "prompt.plainLanguage.content": "Explain the following for a beginner.\n\nStart with the conclusion, then add only the background needed to understand it.",
        "prompt.effectiveCollaboration.title": "Help AI complete a task effectively",
        "prompt.effectiveCollaboration.content": "Goal: {{feature description}}.\n\nConstraints and references: {{technical constraints}}.\n\nRestate the intended result and boundaries, and identify any critical missing information. Once the information is sufficient, complete the task directly.\n\nBefore finishing, run any available tests, builds, or comparison checks, fix the issues found, and provide a concise list of changes and verification evidence.",
        "prompt.requirementsInterview.title": "Interview first, then write the specification",
        "prompt.requirementsInterview.content": "I want to implement {{feature description}}, with these constraints: {{technical constraints}}.\n\nInterview me step by step about user experience, scope, edge cases, data and security, technical tradeoffs, and acceptance criteria. Do not ask obvious questions.\n\nOnce enough information is available, produce a self-contained specification with goals, non-goals, key flows, failure scenarios, and end-to-end acceptance steps.\n\nDo not modify code at this stage.",
        "prompt.explorePlanImplement.title": "Explore and plan before implementing",
        "prompt.explorePlanImplement.content": "Complete {{feature description}} while following {{technical constraints}}.\n\nFirst inspect the relevant code, existing tests, and project conventions without making changes. Confirm the real call chain and reusable patterns.\n\nThen provide the smallest implementation plan and acceptance criteria.\n\nImplement the plan.\n\nFinally, run the most relevant tests and static checks, fix failures, and report the changed files, key tradeoffs, and verification results.",
        "prompt.rootCause.title": "Find and fix the root cause",
        "prompt.rootCause.content": "Observed problem: {{feature description}}.\n\nEnvironment, logs, or constraints: {{technical constraints}}.\n\nReproduce the problem and trace the call chain to find the root cause. Do not hide symptoms by swallowing errors, skipping checks, or hard-coding around them.\n\nAdd a deterministic failing test first, then make the smallest fix.\n\nRun the relevant tests and builds until they pass, and provide the root cause, why the fix works, and verification evidence.",
        "prompt.codeReview.title": "Review code changes",
        "prompt.codeReview.content": "Review {{feature description}}, focusing on {{technical constraints}}.\n\nFirst understand the change goal and project conventions. Then check correctness, data-loss and compatibility risks, security, concurrency and performance, architectural consistency, and test gaps.\n\nReport only actionable, evidence-backed issues, ordered as blocking, important, and suggestion. For each issue, include the file and location, impact, trigger, and smallest recommended fix.\n\nIf no issues are found, state the remaining risks and the scope reviewed.",
        "prompt.testGeneration.title": "Add high-value tests",
        "prompt.testGeneration.content": "Add tests for {{feature description}} while following {{technical constraints}}.\n\nRead the implementation and existing test style first. Identify critical paths, boundary values, error scenarios, and historically fragile behavior.\n\nPrefer deterministic tests of observable outcomes; avoid testing implementation details or using unnecessary mocks.\n\nRun the relevant tests, fix failures introduced by this work, and explain the risk covered by each new test.",
        "prompt.refactor.title": "Make the smallest behavior-preserving refactor",
        "prompt.refactor.content": "Refactor {{feature description}} under these constraints: {{technical constraints}}.\n\nUse existing tests and any necessary characterization tests to lock down observable behavior. Then identify the specific complexity and the smallest refactoring boundary.\n\nKeep public interfaces and behavior unchanged, and do not expand the feature incidentally. Work in small steps and run tests continuously.\n\nFinally, compare before and after, explaining what became simpler, which behaviors were verified, and what risks remain.",
        "prompt.outcomeContract.title": "Complete complex work with an outcome contract",
        "prompt.outcomeContract.content": "Role: You are the collaborator responsible for delivering {{feature description}}.\n\nGoal: Define the user-visible outcome first, then choose the most effective path to achieve it.\n\nSuccess criteria: The result is complete, follows {{technical constraints}}, supports key decisions with verifiable evidence, and passes all required checks.\n\nAutonomy boundary: Safe in-scope reading, analysis, editing, and verification may proceed directly. Confirm before external writes, destructive actions, paid actions, or scope expansion.\n\nOutput: Lead with the result, followed by key evidence, completed actions, and blockers.\n\nStop rule: Finish when evidence is sufficient. Ask only for the minimum missing information when blocked. If verification fails, fix and retry instead of masking the root cause.",
        "prompt.audit.title": "Streamline and calibrate a prompt",
        "prompt.audit.content": "Review and improve this prompt: {{feature description}}.\n\nIts use case and immutable constraints are: {{technical constraints}}.\n\nPreserve user-visible outcomes, success criteria, stopping conditions, safety and permission boundaries, evidence requirements, tool routing, and output format. Remove repeated rules, ineffective examples, process instructions the model already follows reliably, and irrelevant tools.\n\nFind contradictory rules or excessive use of words such as always, never, and only, and replace them with clear decision conditions.\n\nOutput the streamlined prompt, the removed or rewritten items with reasons, and representative tests comparing the old and new prompts.\n\nDo not introduce unrelated rules without an observed need.",
        "prompt.research.title": "Research with clear evidence boundaries",
        "prompt.research.content": "Research {{feature description}} within these source constraints: {{technical constraints}}.\n\nStart with one broad search using short, distinctive keywords. Continue searching only when core facts, dates, owners, identifiers, specified materials, or key claims still lack support.\n\nCite only sources you actually read, placing citations next to the claims they support. Distinguish facts directly supported by sources from inferences and explain source conflicts.\n\nAbsence of evidence does not prove a claim false. When evidence is insufficient, narrow the conclusion or identify the missing information instead of guessing.\n\nOutput the conclusion, key evidence, disagreements or uncertainty, and next steps.",
        "prompt.tags.development": "feature development,implementation",
        "prompt.tags.plainLanguage": "explanation,beginner",
        "prompt.tags.collaboration": "collaboration,acceptance",
        "prompt.tags.requirements": "requirements,interview",
        "prompt.tags.planning": "planning,implementation",
        "prompt.tags.debugging": "debugging,root cause",
        "prompt.tags.codeReview": "code review,quality",
        "prompt.tags.testing": "testing,regression",
        "prompt.tags.refactor": "refactoring,compatibility",
        "prompt.tags.outcome": "outcome contract,delivery",
        "prompt.tags.audit": "prompt optimization,evaluation",
        "prompt.tags.research": "research,evidence"
    ]

    private static let simplifiedChinese: [String: String] = [
        "menu.show": "显示 funPaste",
        "menu.resume": "恢复记录剪贴板",
        "menu.pause": "暂停记录剪贴板",
        "menu.clear": "清空剪贴历史",
        "menu.quit": "退出 funPaste",
        "common.cancel": "取消",
        "common.copy": "复制",
        "common.delete": "删除",
        "common.edit": "编辑",
        "common.restore": "恢复",
        "common.archive": "归档",
        "common.save": "保存",
        "common.create": "创建",
        "common.favorites": "收藏",
        "common.category": "分类",
        "common.items.count": "%d 个项目",
        "settings.title": "funPaste 设置",
        "settings.launchAtLogin": "开机时启动",
        "settings.launchAtLogin.requiresApproval": "请在系统设置中允许 funPaste，以完成开机自启动设置。",
        "settings.launchAtLogin.unavailable": "当前这份 funPaste 无法设置开机自启动。",
        "settings.launchAtLogin.openSystemSettings": "打开登录项设置",
        "settings.historyLimit": "剪贴历史上限",
        "settings.historyLimit.count": "%d 条",
        "close.funPaste": "关闭 funPaste",
        "category.switch": "切换到%@",
        "category.recent": "最近复制",
        "category.prompt": "Prompt",
        "category.pinned": "收藏",
        "category.image": "图片",
        "category.file": "文件",
        "category.recent.headline": "刚复制，也最应该先看到",
        "category.prompt.headline": "把好问题留在触手可及处",
        "category.pinned.headline": "真正值得反复使用的内容",
        "category.image.headline": "刚复制的图片，也在这里",
        "category.file.headline": "文件引用，不再散落在记忆里",
        "empty.title": "没有找到相关内容",
        "empty.description": "换个关键词，或切换分类继续浏览。",
        "prompt.new": "新建 Prompt",
        "favorite.new": "新建收藏",
        "editor.close": "关闭内容编辑",
        "editor.prompt.new": "新建 Prompt",
        "editor.favorite.new": "新建收藏",
        "editor.prompt.edit": "编辑 Prompt",
        "editor.favorite.edit": "编辑收藏",
        "editor.variablesHint": "可使用 {{功能描述}}、{{技术约束}} 作为变量",
        "editor.prompt.titlePlaceholder": "标题，例如：实现一个新功能",
        "editor.favorite.titlePlaceholder": "标题，例如：常用收件地址",
        "editor.prompt.contentPlaceholder": "示例：请帮我完成……",
        "editor.favorite.contentPlaceholder": "填写需要长期保留的内容",
        "editor.primaryCollection": "主分类",
        "editor.tagsPlaceholder": "标签，用逗号分隔",
        "editor.sourceURLPlaceholder": "来源链接（可选）",
        "search.prompt": "搜索 Prompt、标签或来源",
        "search.category": "搜索%@",
        "delete.warning": "删除后无法恢复",
        "delete.confirmation": "确定删除“%@”吗？",
        "delete.permanently": "永久删除",
        "prompt.sort": "Prompt 排序",
        "prompt.filter.all": "全部",
        "prompt.filter.favorites": "收藏",
        "prompt.filter.archived": "已归档",
        "prompt.favorite": "收藏 Prompt",
        "prompt.unfavorite": "取消收藏 Prompt",
        "favorite.add": "收藏",
        "favorite.added": "已收藏",
        "content.manage.prompt": "管理 Prompt",
        "content.manage.favorite": "管理收藏",
        "feedback.unpinned": "已取消收藏“%@”",
        "feedback.pinned": "已收藏“%@”",
        "feedback.promptFavorited": "已收藏 Prompt“%@”",
        "feedback.promptUnfavorited": "已取消收藏 Prompt“%@”",
        "feedback.archived": "已归档“%@”",
        "feedback.restored": "已恢复“%@”",
        "feedback.emptyFields": "标题和内容都不能为空",
        "feedback.duplicate": "已有相同内容：“%@”",
        "feedback.saved": "已保存“%@”",
        "feedback.deleted": "已删除“%@”",
        "feedback.paused": "已暂停记录剪贴板",
        "feedback.resumed": "已恢复记录剪贴板",
        "feedback.historyCleared": "已清空剪贴历史",
        "feedback.historyLimit": "历史记录上限已设为 %d 条",
        "feedback.fileMissing": "文件已被移动或删除，已从历史中移除",
        "feedback.someFilesMissing": "部分文件已失效，仅复制现有文件",
        "feedback.copiedManualPaste": "已复制，请手动粘贴",
        "feedback.pasted": "已粘贴“%@”",
        "promptComposer.title": "使用 Prompt",
        "promptComposer.templateContext": "模板上下文",
        "promptComposer.templateDescription": "模板保持只读，填写内容只会生成一次性的 Prompt。",
        "promptComposer.featureDescription": "功能描述",
        "promptComposer.featureVariable": "替换模板中的 {{功能描述}}",
        "promptComposer.featureGuidance": "详细描述目标、用户场景和期望结果",
        "promptComposer.technicalConstraints": "技术约束",
        "promptComposer.technicalVariable": "替换模板中的 {{技术约束}}",
        "promptComposer.technicalGuidance": "填写技术栈、兼容性、范围或不能改变的行为",
        "promptComposer.additionalContext": "补充上下文",
        "promptComposer.additionalDescription": "可选。粘贴日志、代码、参考资料或其他长文本。",
        "promptComposer.additionalGuidance": "输入或粘贴补充信息",
        "promptComposer.preview": "生成结果预览",
        "promptComposer.previewReady": "将复制或粘贴以下完整内容。",
        "promptComposer.previewIncomplete": "请先填写模板中的必填变量。",
        "promptComposer.guidance": "填写提示：%@",
        "promptComposer.generateAndPaste": "生成并粘贴",
        "promptComposer.additionalSection": "补充上下文：",
        "collection.inbox": "收件箱",
        "collection.development": "开发",
        "collection.research": "研究",
        "collection.writing": "写作",
        "collection.productDesign": "产品设计",
        "collection.personal": "个人",
        "sort.smart": "智能排序",
        "sort.recentlyUsed": "最近使用",
        "sort.recentlyAdded": "最近添加",
        "sort.name": "按名称",
        "history.source.clipboard": "剪贴板",
        "history.image.title": "剪贴图片",
        "history.image.description": "图片 \u{00b7} %@",
        "history.files.count": "%d 个文件",
        "library.source.customPrompt": "自定义 Prompt",
        "library.source.favorite": "收藏",
        "demo.productPrinciple.title": "产品体验优先的实现原则",
        "demo.productPrinciple.content": "我只负责把控需求；技术方案、架构和实现细节由你决定。首要原则是保证用户体验。",
        "demo.productPrinciple.source": "备忘录",
        "demo.swiftUIFocus.title": "SwiftUI 卡片焦点状态",
        "demo.appleHIG.content": "设计应该清晰、可预测，并尊重用户已掌握的系统习惯。",
        "demo.address.title": "常用收件地址",
        "demo.address.content": "上海市静安区 \u{00b7} 个人工作室 \u{00b7} 请提前联系确认收件时间",
        "demo.palette.title": "柔和日落色板",
        "demo.palette.content": "温暖柑橘、雾紫与深墨蓝的配色参考",
        "demo.palette.source": "截图",
        "demo.file.title": "funPaste 产品想法.md",
        "demo.file.content": "剪贴历史、常用内容和 Prompt 模板的一体化整理方案。",
        "prompt.source.builtIn": "内置 Prompt",
        "prompt.source.claude": "Claude Code 最佳实践",
        "prompt.source.github": "GitHub 工程实践",
        "prompt.source.openAI": "OpenAI GPT-5.6 指南",
        "prompt.development.title": "请帮我完成这个功能",
        "prompt.development.content": "请帮我完成{{功能描述}}。\n\n技术约束：{{技术约束}}。\n\n先阅读项目结构，说明修改方案，修改代码并运行检查。",
        "prompt.plainLanguage.title": "把复杂内容说清楚",
        "prompt.plainLanguage.content": "请用面向初学者的中文解释以下内容。\n\n先给结论，再补充必要的背景。",
        "prompt.effectiveCollaboration.title": "让 AI 高效完成任务",
        "prompt.effectiveCollaboration.content": "目标：{{功能描述}}。\n\n约束与参考：{{技术约束}}。\n\n先复述你理解的结果和边界，指出缺失的关键信息；信息足够后直接完成任务。\n\n结束前运行可用的测试、构建或对比检查，修复发现的问题，并用简短清单给出改动与验证证据。",
        "prompt.requirementsInterview.title": "先访谈，再写需求规格",
        "prompt.requirementsInterview.content": "我想实现{{功能描述}}，当前约束是{{技术约束}}。\n\n先围绕用户体验、范围、边界情况、数据与安全、技术取舍和验收标准逐步访谈我；不要问显而易见的问题。\n\n信息充分后，输出一份自包含的规格，明确目标、非目标、关键流程、异常场景和端到端验收步骤。\n\n此阶段不要修改代码。",
        "prompt.explorePlanImplement.title": "先探索规划，再实现",
        "prompt.explorePlanImplement.content": "请完成{{功能描述}}，并遵守{{技术约束}}。\n\n先只读探索相关代码、现有测试和项目约定，确认真实调用链与可复用模式。\n\n再列出最小修改计划和验收标准。\n\n随后按计划实现。\n\n完成后运行最相关的测试和静态检查，修复失败，并报告修改文件、关键取舍和验证结果。",
        "prompt.rootCause.title": "定位并修复根因",
        "prompt.rootCause.content": "问题现象：{{功能描述}}。\n\n环境、日志或限制：{{技术约束}}。\n\n先复现问题并沿调用链定位根因，不要通过吞掉错误、跳过检查或硬编码绕过症状。\n\n先添加能稳定复现的失败测试，再做最小修复。\n\n运行相关测试与构建直到通过，并提供根因、修复原理和验证证据。",
        "prompt.codeReview.title": "审查代码变更",
        "prompt.codeReview.content": "请审查{{功能描述}}，重点关注{{技术约束}}。\n\n先理解变更目标和项目约定，再检查正确性、数据丢失与兼容性风险、安全、并发与性能、架构一致性以及测试缺口。\n\n只报告可操作且有证据的问题，按阻塞、重要、建议排序；每项注明文件与位置、影响、触发场景和最小修复建议。\n\n若没有问题，明确说明剩余风险和已检查范围。",
        "prompt.testGeneration.title": "补齐高价值测试",
        "prompt.testGeneration.content": "请为{{功能描述}}补齐测试，遵守{{技术约束}}。\n\n先阅读实现和现有测试风格，识别关键路径、边界值、错误场景和曾经容易回归的行为。\n\n优先写确定性强、验证可观察结果的测试，避免测试实现细节和不必要的 Mock。\n\n运行相关测试，修复由本次工作引入的失败，并说明每个新增测试防住了什么风险。",
        "prompt.refactor.title": "保持行为的最小重构",
        "prompt.refactor.content": "请重构{{功能描述}}，约束是{{技术约束}}。\n\n先用现有测试和必要的特征测试锁定当前可观察行为，再指出具体复杂度与最小重构边界。\n\n保持公共接口和行为不变，不顺手扩展功能；分小步修改并持续运行测试。\n\n最后对比重构前后，说明简化了什么、哪些行为得到验证，以及仍未处理的风险。",
        "prompt.outcomeContract.title": "用结果契约完成复杂任务",
        "prompt.outcomeContract.content": "角色：你是负责交付{{功能描述}}的协作助手。\n\n目标：先明确用户可见的最终结果，再选择最有效的完成路径。\n\n成功标准：结果完整、符合{{技术约束}}，关键判断有可核查证据，要求的检查全部通过。\n\n自主边界：安全且范围内的读取、分析、修改和验证可直接进行；外部写入、破坏性操作、付费行为或扩大范围前必须确认。\n\n输出：先给结论，再给关键证据、完成动作和阻塞项。\n\n停止规则：已有充分证据时结束；缺少必要信息时只询问最小缺失字段；验证失败时修复并重试，不用表面绕过代替根因解决。",
        "prompt.audit.title": "精简并校准 Prompt",
        "prompt.audit.content": "请审查并优化以下 Prompt：{{功能描述}}。\n\n使用场景与不可改变的约束：{{技术约束}}。\n\n保留用户可见结果、成功标准、停止条件、安全与权限边界、证据要求、工具路由和输出格式；删除重复规则、无效示例、模型已能稳定完成的过程说明及无关工具。\n\n找出互相矛盾或过度使用“始终、绝不、只能”的规则，并改成清晰的判断条件。\n\n输出精简后的 Prompt、删除或改写项及原因，以及一组用于对比新旧 Prompt 的代表性测试。\n\n不要一次引入与已观察问题无关的新规则。",
        "prompt.research.title": "做有证据边界的研究",
        "prompt.research.content": "请研究{{功能描述}}，来源范围与限制为{{技术约束}}。\n\n先用简短且有区分度的关键词做一次广泛检索；只有当核心事实、日期、负责人、标识、指定材料或关键主张仍缺少支持时再继续检索。\n\n只引用实际读取的来源，把引用放在对应主张旁；明确区分来源直接支持的事实与推断，说明来源冲突。\n\n没有证据不等于事实为否；证据不足时缩小结论或明确缺失信息，不猜测。\n\n输出结论、关键证据、分歧或不确定性和下一步。",
        "prompt.tags.development": "功能开发,实现",
        "prompt.tags.plainLanguage": "解释,初学者",
        "prompt.tags.collaboration": "协作,验收",
        "prompt.tags.requirements": "需求,访谈",
        "prompt.tags.planning": "规划,实现",
        "prompt.tags.debugging": "调试,根因",
        "prompt.tags.codeReview": "代码审查,质量",
        "prompt.tags.testing": "测试,回归",
        "prompt.tags.refactor": "重构,兼容性",
        "prompt.tags.outcome": "结果契约,交付",
        "prompt.tags.audit": "Prompt 优化,评估",
        "prompt.tags.research": "研究,证据"
    ]
}
